### ISSUE TITLE
CSS styles 

### ISSUE THREAD

**Issue by scottsteinbeck** [jcberquist/commandbox-cfformat#153]
on my .cfm pages, sometimes I will have on-page css styles. The styles seem to get formatted without indentation 

```css
.navbar .nav-item    {
    position: relative;
}        
```

Gets formatted to

```css
.navbar .nav-item    {
position: relative;
}    
```
